media: public/img

content:
  - name: home
    label: Home
    type: file
    path: content/home/index.md
    fields:
      - { name: title, label: Título, type: string }

      - name: slides
        label: Slider
        type: list
        fields:
          - { name: image, label: Imagem, type: image, required: true }
          - { name: title, label: Título, type: string }
          - { name: subtitle, label: Subtítulo, type: string }

      - name: actuacion
        label: Atuación
        type: list
        fields:
          - { name: icon, label: Ícone, type: image }
          - { name: title, label: Título, type: string }
          - { name: text, label: Texto, type: text }

      - name: testimonials
        label: Testimonios
        type: list
        fields:
          - { name: name, label: Nome, type: string }
          - { name: text, label: Texto, type: text }

      - name: gallery
        label: Galeria
        type: list
        field: { name: image, label: Imagem, type: image }

  # === Contato ===
  - name: contato
    label: Contato
    type: file
    path: content/contato/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
  
      - name: title
        label: Título da página
        type: string
  
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
  
      - name: body
        label: Corpo do conteúdo
        type: rich-text


  
  # === Eventos ===
  - name: events
    label: Eventos
    type: collection
    path: content/events
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }



  # === Blog ===
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
  # === Metadata (site-wide) ===
  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code
