media: public/img

content:
  - name: home
    label: Home
    type: file
    path: content/index.njk
    fields:

      - { name: title, label: Título, type: string }

      # ===== SLIDER =====
      - name: slides
        label: Slider
        type: object
        list: true
        fields:
          - { name: image, label: Imagem, type: image, required: true }
          - { name: title, label: Título, type: string }
          - { name: subtitle, label: Subtítulo, type: string }

      # ===== ATUACIÓN =====
      - { name: actuacion_title, label: Título Atuación, type: string }
      - { name: actuacion_text, label: Texto Atuación, type: text }

      - name: actuacion
        label: Itens de Atuación
        type: object
        list: true
        fields:
          - { name: icon, label: Ícone, type: image }
          - { name: title, label: Título, type: string }

      # ===== VISIÓN =====
      - { name: vision_title, label: Título Visión, type: string }
      - { name: vision_text, label: Texto Visión, type: text }

      # ===== TESTIMONIOS =====
      - name: testimonials
        label: Testimonios
        type: object
        list: true
        fields:
          - { name: name, label: Nome, type: string }
          - { name: text, label: Texto, type: text }

      # ===== GALERIA =====
      - name: gallery
        label: Galeria
        type: object
        list: true
        fields:
          - { name: image, label: Imagem, type: image }

  # === Contato ===
  - name: contato
    label: Contato
    type: file
    path: content/contato/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
  
      - name: title
        label: Título da página
        type: string
  
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
  
      - name: body
        label: Corpo do conteúdo
        type: rich-text


  
  # === Eventos ===
  - name: events
    label: Eventos
    type: collection
    path: content/events
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: image, label: Image, type: image } 
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }


  # === Blog ===
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: image, label: Image, type: image } 
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }

  # === Metadata (site-wide) ===
  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code
