media: public/img

# === Metadata (site-wide) ===
- name: metadata
  label: Metadata
  type: file
  path: _data/metadata.js
  format: code

# === Blog Posts ===
- name: blog_posts
  label: "Blog Posts"
  type: folder
  folder: content/blog
  create: true
  delete: true
  extension: md
  format: frontmatter
  fields:
    - name: title
      label: "Título"
      widget: string
    - name: body
      label: "Conteúdo"
      widget: markdown
